"""empty message

Revision ID: 1622ec58308e
Revises: 8c3f3cbff070
Create Date: 2021-04-27 16:50:48.074418

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "1622ec58308e"
down_revision = "8c3f3cbff070"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
