"""empty message

Revision ID: 4e609a88900f
Revises: 69a91d6b94f0
Create Date: 2021-04-27 17:21:52.313249

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "4e609a88900f"
down_revision = "69a91d6b94f0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
