"""empty message

Revision ID: 69a91d6b94f0
Revises: 1622ec58308e
Create Date: 2021-04-27 17:18:39.347511

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "69a91d6b94f0"
down_revision = "1622ec58308e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
