"""empty message

Revision ID: 8c3f3cbff070
Revises: e689688e0ece
Create Date: 2021-04-27 16:47:04.711596

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "8c3f3cbff070"
down_revision = "e689688e0ece"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
