"""empty message

Revision ID: c818e54206e0
Revises: cf384a15c9b4
Create Date: 2021-04-27 16:22:56.240201

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "c818e54206e0"
down_revision = "cf384a15c9b4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
