"""empty message

Revision ID: e689688e0ece
Revises: c818e54206e0
Create Date: 2021-04-27 16:45:47.214226

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "e689688e0ece"
down_revision = "c818e54206e0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
